export const   GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const  GET_PRODUCTS_SUCCESS = ' GET_PRODUCTS_SUCCESS'
export const   GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'

export const ADD_PRODUCT_CART_REQUEST = 'ADD_PRODUCT_CART_REQUEST'
export const ADD_PRODUCT_CART_SUCCESS = 'ADD_PRODUCT_CART_SUCCESS'
export const ADD_PRODUCT_CART_FAILURE = 'ADD_PRODUCT_CART_FAILURE'

export const  DELETE_PRODUCT_CART_REQUEST = 'DELETE_PRODUCT_CART_REQUEST'
export const  DELETE_PRODUCT_CART_SUCCESS = 'DELETE_PRODUCT_CART_SUCCESS'
export const  DELETE_PRODUCT_CART_FAILURE = 'DELETE_PRODUCT_CART_FAILURE'
