export const GET_NEWARRIVAL = "GET_NEWARRIVAL";
export const GET_NEWARRIVAL_SUCCESS = "GET_NEWARRIVAL_SUCCESS";
export const GET_NEWARRIVAL_FAILURE = "GET_NEWARRIVAL_FAILURE";

export const GET_SHIRT = "GET_SHIRT";
export const GET_SHIRT_SUCCESS = "GET_SHIRT_SUCCESS";
export const GET_SHIRT_FAILURE = "GET_SHIRT_FAILURE";

export const GET_TSHIRT = "GET_TSHIRT";
export const GET_TSHIRT_SUCCESS = "GET_TSHIRT_SUCCESS";
export const GET_TSHIRT_FAILURE = "GET_TSHIRT_FAILURE";

export const GET_TROUSER = "GET_TROUSER";
export const GET_TROUSER_SUCCESS = "GET_TROUSER_SUCCESS";
export const GET_TROUSER_FAILURE = "GET_TROUSER_FAILURE";

export const GET_DENIMS = "GET_DENIMS";
export const GET_DENIMS_SUCCESS = "GET_DENIMS_SUCCESS";
export const GET_DENIMS_FAILURE = "GET_DENIMS_FAILURE";

export const GET_SHORTS = "GET_SHORTS";
export const GET_SHORTS_SUCCESS = "GET_SHORTS_SUCCESS";
export const GET_SHORTS_FAILURE = "GET_SHORTS_FAILURE";

export const GET_SWEATERS = "GET_SWEATERS";
export const GET_SWEATERS_SUCCESS = "GET_SWEATERS_SUCCESS";
export const GET_SWEATERS_FAILURE = "GET_SWEATERS_FAILURE";




export const  DELETE_PRODUCT_CART_REQUEST = 'DELETE_PRODUCT_CART_REQUEST'
export const  DELETE_PRODUCT_CART_SUCCESS = 'DELETE_PRODUCT_CART_SUCCESS'
export const  DELETE_PRODUCT_CART_FAILURE = 'DELETE_PRODUCT_CART_FAILURE'

 



